# Prueba de implementaciones para signatures

In [1]:
import sys
sys.path.append('../source')

from ray_track import *

In [2]:
media_trail = [2, 1]
interfaces = [2, 1]

myRay = Ray(media_trail, interfaces)
mySurface = Surface(myRay)
mySurface.get_cases()

[['P', 'P'], ['P', 'S'], ['S', 'P'], ['S', 'S']]

In [3]:
myTrack = Trajectory(myRay, mySurface)
myTrack.get_signatures()

[[[4, 2], 2], [[4, 2], 3], [[5, 2], 2], [[5, 2], 3]]

In [4]:
myTrack.pretty_print_signatures()


Signatures for trail [2, 1] :

['P', 'P'] = [[4, 2], 2]
['P', 'S'] = [[4, 2], 3]
['S', 'P'] = [[5, 2], 2]
['S', 'S'] = [[5, 2], 3]


In [2]:
import numpy as np

In [3]:
def F(X):
    x1, x2, x3 = X
    f1 = 3*x1 - np.cos(x2*x3) - 0.5
    f2 = x1**2 - 81*(x2 + 0.1)**2 + np.sin(x3) + 1.06
    f3 = np.exp(-x1*x2) + 20*x3 + (10*np.pi - 3)/3
    return np.array([f1, f2, f3])

x0 = np.zeros((3,3))

example = F(x0)

m1 = example.copy()

np.fill_diagonal(m1, m1.diagonal() + 0.0)

m1

array([[-1.5       , -1.5       , -1.5       ],
       [ 0.25      ,  0.25      ,  0.25      ],
       [10.47197551, 10.47197551, 10.47197551]])

In [16]:
a, b, c = m1

a

array([-1.5, -1.5, -1.5])

In [4]:
v1 = np.array((1.0, 2.0, 3.0))

m2 = np.repeat(v1, 3).reshape(3, 3)

np.fill_diagonal(m2, m2.diagonal() + 1e-3)

m2

array([[1.001, 1.   , 1.   ],
       [2.   , 2.001, 2.   ],
       [3.   , 3.   , 3.001]])

In [30]:
from scipy.optimize import approx_fprime

x0 = np.array((0.,0.,0.))

approx_fprime( x0, F, 1e-4 )

array([[ 3.00000000e+00,  0.00000000e+00,  0.00000000e+00],
       [ 1.00000001e-04, -1.62081000e+01,  9.99999998e-01],
       [ 0.00000000e+00,  0.00000000e+00,  2.00000000e+01]])

In [31]:
from homotopy import *

In [32]:
get_jacobian(F, x0, h=1e-4)

array([[  3. ,   0. ,   0. ],
       [  0. , -16.2,   1. ],
       [  0. ,   0. ,  20. ]])

In [29]:
%time approx_fprime( x0, F, 1e-5 )

CPU times: total: 0 ns
Wall time: 0 ns


array([[ 3.00000000e+00, -6.75861778e+00, -1.50196129e+00],
       [ 8.00001000e+00, -3.40200810e+02, -9.11132321e-01],
       [-6.70917188e-04, -1.34182301e-03,  2.00000000e+01]])

In [27]:
%time get_jacobian(F, x0, h=1e-5)

CPU times: total: 0 ns
Wall time: 0 ns


array([[ 3.00000000e+00, -6.75888521e+00, -1.50197449e+00],
       [ 8.00000000e+00, -3.40200000e+02, -9.11130260e-01],
       [-6.70924294e-04, -1.34185001e-03,  2.00000000e+01]])