# Prueba de implementaciones para signatures

In [1]:
import sys
sys.path.append('../source')

from ray_track import *

In [2]:
media_trail = [2, 1]
interfaces = [2, 1]

myRay = Ray(media_trail, interfaces)
mySurface = Surface(myRay)
mySurface.get_cases()

[['P', 'P'], ['P', 'S'], ['S', 'P'], ['S', 'S']]

In [3]:
myTrack = Trajectory(myRay, mySurface)
myTrack.get_signatures()

[[[4, 2], 2], [[4, 2], 3], [[5, 2], 2], [[5, 2], 3]]

In [4]:
myTrack.pretty_print_signatures()


Signatures for trail [2, 1] :

['P', 'P'] = [[4, 2], 2]
['P', 'S'] = [[4, 2], 3]
['S', 'P'] = [[5, 2], 2]
['S', 'S'] = [[5, 2], 3]


In [5]:
import numpy as np

In [6]:
def F(X):
    x1, x2, x3 = X
    f1 = 3*x1 - np.cos(x2*x3) - 0.5
    f2 = x1**2 - 81*(x2 + 0.1)**2 + np.sin(x3) + 1.06
    f3 = np.exp(-x1*x2) + 20*x3 + (10*np.pi - 3)/3
    return np.array([f1, f2, f3])

x0 = np.zeros((3,3))

example = F(x0)

m1 = example.copy()

np.fill_diagonal(m1, m1.diagonal() + 0.0)

m1

array([[-1.5       , -1.5       , -1.5       ],
       [ 0.25      ,  0.25      ,  0.25      ],
       [10.47197551, 10.47197551, 10.47197551]])

In [7]:
a, b, c = m1

a

array([-1.5, -1.5, -1.5])

In [8]:
v1 = np.array((1.0, 2.0, 3.0))

m2 = np.repeat(v1, 3).reshape(3, 3)

np.fill_diagonal(m2, m2.diagonal() + 1e-3)

m2

array([[1.001, 1.   , 1.   ],
       [2.   , 2.001, 2.   ],
       [3.   , 3.   , 3.001]])

In [9]:
from scipy.optimize import approx_fprime

x0 = np.array((0.,0.,0.))

approx_fprime( x0, F, 1e-4 )

array([[ 3.00000000e+00,  0.00000000e+00,  0.00000000e+00],
       [ 1.00000001e-04, -1.62081000e+01,  9.99999998e-01],
       [ 0.00000000e+00,  0.00000000e+00,  2.00000000e+01]])

In [10]:
from homotopy import *

In [11]:
get_jacobian(F, x0, h=1e-4)

array([[  3. ,   0. ,   0. ],
       [  0. , -16.2,   1. ],
       [  0. ,   0. ,  20. ]])

In [12]:
%time approx_fprime( x0, F, 1e-5 )

CPU times: total: 0 ns
Wall time: 299 µs


array([[ 3.00000000e+00,  0.00000000e+00,  0.00000000e+00],
       [ 1.00000008e-05, -1.62008100e+01,  1.00000000e+00],
       [ 0.00000000e+00,  0.00000000e+00,  2.00000000e+01]])

In [13]:
%time get_jacobian(F, x0, h=1e-3)

CPU times: total: 0 ns
Wall time: 0 ns


array([[  3.        ,   0.        ,   0.        ],
       [  0.        , -16.2       ,   0.99999983],
       [  0.        ,   0.        ,  20.        ]])

In [14]:
# probando el proceso de homotopia

# definiendo funcion
def F(X):
    x1, x2, x3 = X
    f1 = 3*x1 - np.cos(x2*x3) - 0.5
    f2 = x1**2 - 81*(x2 + 0.1)**2 + np.sin(x3) + 1.06
    f3 = np.exp(-x1*x2) + 20*x3 + (10*np.pi - 3)/3
    return np.array([f1, f2, f3])

# definiendo X0
X0 = np.array((0.0, 0.0, 0.0))

# obteniendo solucion
get_solution(F, X0, h=0.01)

array([ 5.00000000e-01,  5.21819214e-13, -5.23598776e-01])

In [15]:
np.arange(0.0, 1+1, 1)

array([0., 1.])

In [16]:
int(1/0.015)

66